---
- hosts: all
  become: true
  tasks:
  - name: Set ip_forward kernel param to true
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      reload: yes 
  
  - name: Remove docker packages
    yum: 
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-common
      - docker-selinux
      - docker-engine

  - name: Install required docker packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - centos-release-openshift-origin

  - name: Add the docker-ce repository
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker-CE
    yum:
      name: docker-ce
      state: latest

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
      

  - name: Create directory path /etc/docker
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: Configure docker insecure registries
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0644  

  - name: Reload systemd and restart docker
    systemd:
      name: docker
      enabled: True
      state: restarted
      daemon_reload: yes

  - name: Start and enable firewalld
    systemd:
      name: firewalld
      enabled: True
      state: started

  - name: Get Docker Bridge Network Subnet
    shell: docker network inspect -f "{{ '{{' }} range .IPAM.Config {{ '}}' }}{{ '{{' }} .Subnet {{ '}}' }}{{ '{{' }}end{{ '}}' }}" bridge
    register: docker_bridge_subnet

  - name: Check value of variable
    debug:
      var: docker_bridge_subnet.stdout
    
  - name: Create dockerc firewalld zone
    shell: |
      firewall-cmd --permanent --new-zone dockerc
      firewall-cmd --reload
    ignore_errors: True

  - name: Configure Firewalld Source Network
    firewalld:
      zone: dockerc
      source: "{{ docker_bridge_subnet.stdout }}"
      state: enabled

  - name: Configure Firewalld 8443/tcp
    firewalld:
      zone: dockerc
      port: 8443/tcp
      state: enabled
      permanent: True  
      
  - name: Configure Firewalld 53/udp
    firewalld:
      zone: dockerc
      port: 53/udp
      state: enabled
      permanent: True  

  - name: Configure Firewalld 8053/udp
    firewalld:
      zone: dockerc
      port: 8053/udp
      state: enabled
      permanent: True  

  - name: Install Origin Client
    yum:
      name: origin-clients
      state: latest

  - name: Git clone oc-cluster-wrapper
    shell: git clone https://github.com/openshift-evangelists/oc-cluster-wrapper && chown -R vagrant:docker oc-cluster-wrapper

  - name: OC Cluster Wrapper Up
    shell: oc-cluster-wrapper/oc-cluster up --public-hostname=`hostname -i`